### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by aflavio** [sunaku/tamzen-font#11]
Hi. 

I got a problem when use this font:
![](http://i.imgur.com/aEzSqyC.png)

Do you know how to fix it ? 

I'm  using xfce-terminal. Debian stretch.

**Comment by sunaku** [comment]
That font doesn't look like Tamzen at all. :disappointed_relieved:  How did you set up **xfce-terminal** to use Tamzen?  [Like this](http://askubuntu.com/questions/283830/how-to-change-the-font-of-various-terminal-emulators)?

![](http://i.stack.imgur.com/DhLFJ.png)

**Comment by aflavio** [comment]
I tried Tamzen, not Monospace. This was the problem. Thanks dude! Now works fine!

**Comment by sunaku** [comment]
Cool, enjoy! :sunglasses:
