### ISSUE TITLE
lambda?

### ISSUE THREAD

**Issue by pcoutin** [sunaku/tamzen-font#12]
There is no λ on this font. Using it with xterm.
Maybe I should do it.

**Comment by sunaku** [comment]
Your system's or application's _fallback font_ should automatically provide that symbol:

![tamzen-lambda](https://cloud.githubusercontent.com/assets/9863/20845724/3a1fbed0-b87b-11e6-8b54-1bef14fe283b.png)

The screenshot above shows [the GTK+ Leafpad application](http://tarot.freeshell.org/leafpad/) rendering the following text:

```
Greetings in various languages:

  Hello world, Καλημέρα κόσμε, コンニチハ
```

**Comment by sunaku** [comment]
@pcoutin I'm closing this issue because it's not a problem if your system or app provides a fallback font (as shown in my previous comment) but feel free to submit a PR that provides a lambda symbol if you wish. :sweat_smile:

**Comment by sunaku** [comment]
You could also try using [the `st` terminal emulator]( http://st.suckless.org/ ), which comes built-in with a Unicode fallback font:

![screenshot](https://cloud.githubusercontent.com/assets/9863/23590681/816d7d10-0199-11e7-9e43-386b3f042eaa.png)
