### ISSUE TITLE
rxvt-unicode-256color does not load tamzen-font properly

### ISSUE THREAD

**Issue by successgo** [sunaku/tamzen-font#16]
Hello, I am going to report an issue:

After installation of tamzen-font, I need to use:

```bash
 xset +fp /usr/local/share/fonts/tamzen-font/bdf
```

to make rxvt-unicode-256color to load this font. 

But if I reboot my system, I need to run the above command again to make it work.

PS. I know a little on `fontconfig` things, is there anything related to this, plus how to resolve it ?

Thank you!

**Comment by sunaku** [comment]
You can add that `xset` line to your [X11 startup file]( http://fluxbox.sourceforge.net/docbook/en/html/app-setup.html ) to have it automatically applied whenever you start X11.  However, depending on your window manager or desktop environment, you might need to put that `xset` line in a completely different file/location/mechanism such as [in a `~/.config/autostart/*.desktop` file](https://pclosmag.com/html/Issues/201009/page10.html).

**Comment by gc5p** [comment]
I have tried to add autostart/tamzen-font.desktop file, but it didn't work.

So neither the .xinitrc and .xsession in my $HOME.

I am using GNOME, it does not work. 
But i3 works. I am eager to know why and how to figure out this.

**Comment by sunaku** [comment]
Which version of GNOME are you using?

**Comment by gaodacheng5percent** [comment]
@sunaku 

OS: Debian GNU/Linux buster/sid 64-bit
GNOME: 3.26.2

```bash
➜  ~ uname -a
Linux debian 4.14.0-3-amd64 #1 SMP Debian 4.14.13-1 (2018-01-14) x86_64 GNU/Linux
```

```bash
➜  ~ urxvt -h
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
```

**Comment by sunaku** [comment]
Closing this issue, as the problem seems to be on the user's end.  Please re-open if you still need help.
