### ISSUE TITLE
Missing character

### ISSUE THREAD

**Issue by im-n1** [sunaku/tamzen-font#19]
I've noticed following character is missing: `ý`
When I try to type this character in Vim it works like undo.

Edit:
This bug is probably not the font issue because when I disable plugin "https://github.com/jiangmiao/auto-pairs" the character works. But interesting is that once I switch to another font the plugin works.

Probably worth to mention this in readme file.

**Comment by sunaku** [comment]
I don't understand how a terminal's font could possibly affect how Vim behaves (treating `ý` as undo). :confounded:

Are you able to reproduce the issue under a different terminal emulator? :thinking: What about in a Linux VT (where no graphical terminal emulator is involved), both with and without this font applied as the console font? :bulb:

**Comment by sunaku** [comment]
Closing due to lack of response.  Please re-open if the problem still affects you.

**Comment by im-n1** [comment]
oh Im sorry... I've already switched to another font...
