### ISSUE TITLE
Some symbols not displaying in Vim-Airline

### ISSUE THREAD

**Issue by UnbatedFlunky** [sunaku/tamzen-font#20]
Some of the Icons are missing in [vim-airline](https://github.com/vim-airline/vim-airlinehttps://github.com/vim-airline/vim-airline)
I'm using URxvt and the [wal.vim](https://github.com/dylanaraps/wal.vim) theme.
.vimrc: 
```
execute pathogen#infect()
syntax on
filetype plugin indent on
set number
set list
set tabstop=2
set shiftwidth=2
set encoding=utf-8

let g:airline_powerline_fonts = 1

colorscheme wal
```
.Xresources: 
```
URxvt*font: -*-unifont-*-*-*-*-*-*-*-*-*-*-*-*
URxvt*font: -misc-tamzen-medium-r-normal--14-101-100-100-c-70-iso8859-1, -misc-tamzenforpowerline-medium-r-normal--14-101-100-100-c-70-iso8859-1, -gnu-unifont-medium-r-normal-sans-16-160-75-75-c-80-iso10646-1
URxvt.boldFont: -misc-tamzen-bold-r-normal--14-101-100-100-c-70-iso8859-1
URxvt.scrollBar: false
URxvt.internalBorder: 10
```

**Comment by sunaku** [comment]
Try viewing this portion of the `Rakefile` in your terminal (you can `cat` it):
https://github.com/sunaku/tamzen-font/blob/master/Rakefile#L285-L290

Do the missing symbols appear now? :thinking: Also, could you post a screenshot?

**Comment by UnbatedFlunky** [comment]
The symbols work without issue in most places, but specifically the "" (LN) symbol doesn't show up in the vim airline like this: ![](https://user-images.githubusercontent.com/8510638/46919342-75274f80-cfde-11e8-905e-54272fb0e4b7.png)

The odd part is that it does work when "greyed out" or just written normally:

![](https://user-images.githubusercontent.com/8510638/46919341-70629b80-cfde-11e8-8635-d8653a3bb603.png)

My latest attempt to fix this has been to change my .vimrc to:
```execute pathogen#infect()
syntax on
filetype plugin indent on
set number
set list
set tabstop=2
set shiftwidth=2
set encoding=utf-8

let g:airline_powerline_fonts = 1

if !exists('g:airline_symbols') 
	let g:airline_symbols = {}
endif

" powerline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = '☰'
let g:airline_symbols.maxlinenr = ''

colorscheme wal
let g:airline_theme='term'


let g:syntastic_python_checkers = ['pylint']
```
and my .Xresources to:
```URxvt*font: -*-unifont-*-*-*-*-*-*-*-*-*-*-*-*
URxvt.boldFont: -misc-tamzen-bold-r-normal--14-101-100-100-c-70-iso8859-1
URxvt*font: -misc-tamzen-medium-r-normal--14-101-100-100-c-70-iso8859-1, -misc-tamzenforpowerline-medium-r-normal--14-101-100-100-c-70-iso8859-1, -gnu-unifont-medium-r-normal-sans-16-160-75-75-c-80-iso10646-1
URxvt.scrollBar: false
URxvt.internalBorder: 10
URxvt.letterSpace: 1
```

The `URxvt.letterSpace: 1` actually made some of the symbols show up, but the issue with "LN" persists.

**Comment by sunaku** [comment]
Thanks for the info. Could you post a screenshot of `cat`ting the Rakefile?
https://github.com/sunaku/tamzen-font/blob/master/Rakefile#L285-L290

```sh
$ sed -n '284,291p' Rakefile | ruby -e 'puts eval STDIN.read'
ABCDEFGHIJKLMNOPQRSTUVWXYZ 12345
abcdefghijklmnopqrstuvwxyz 67890
{}[]()<>$*-+=/#_%^@\&|~?'"`!,.;:
Illegal1i = oO0          
The quick brown fox, (..) Hello,
jumps over lazy dog. /__\ World!
```

For example, here's what I see on my system (running XTerm, not URxvt):
![gh-20](https://user-images.githubusercontent.com/9863/46920061-4341c900-cf9d-11e8-966c-ab19c69896a3.png)

**Comment by UnbatedFlunky** [comment]
absolutely!

![](https://user-images.githubusercontent.com/8510638/46920101-38148a80-cfe9-11e8-8f66-97335013d5de.png)

**Comment by sunaku** [comment]
Excellent! :ok_hand:  Since all the symbols render correctly in the bare terminal (outside Vim), this font is working properly :sweat_smile: and therefore, the root cause of your problem resides within vim-airline itself: I suspect that it may be printing a different Unicode character than the U+E0A1 (the LN symbol) codepoint you see above. :man_shrugging:

**Comment by UnbatedFlunky** [comment]
Fixed the issue by changing font!
