### ISSUE TITLE
Can't seem to figure out different font names for the different sizes in terminal

### ISSUE THREAD

**Issue by cushmatt** [sunaku/tamzen-font#22]
Hi, I'd appreciate a little help if you don't mind.  I'm using Urxvt terminal and currently have it set up like so:

`URxvt*font:     xft:TamzenForPowerline:pixelsize=16`

I have also tried doing it like so:

 `URxvt*font:     xft:-Misc-Tamzen-Medium-R-Normal--16-116-100-100-C-80-ISO8859-1:pixelsize=16`

but for some reason it doesn't recognize the font when I do that.  

I'm using a HiDPI screen so I was really happy that different sizes for your bitmap font along with the powerline symbols.  I had installed via the AUR and all the font sizes appear in my /usr/share/fonts/local/ folder.  However, I can't seem to figure out a way to change the size to something other than the default.  Any help would be greatly appreciated.  

Thanks!

**Comment by sunaku** [comment]
Have you tried the shell `printf` method that is [mentioned in the README]( https://github.com/sunaku/tamzen-font#urxvt-integration ) specifically for URxvt?

```sh
printf '\e]710;%s\007' 'font -misc-tamzen-medium-r-normal--16-108-100-100-c-80-iso8859-1'
```

**Comment by sunaku** [comment]
Another possible issue I just noticed is that you're specifying a different size in your X11 font description:

`URxvt*font: xft:-Misc-Tamzen-Medium-R-Normal--16-`**116**`-100-100-C-80-ISO8859-1`

You may have more success limiting yourself to the predefined X11 font descriptions that are [listed here]( https://github.com/sunaku/tamzen-font#urxvt-integration ).

**Comment by sunaku** [comment]
Closing this issue because it seems to be resolved.  Please re-open if the problem still affects you.
