### ISSUE TITLE
Font Usage

### ISSUE THREAD

**Issue by Sylenss** [sunaku/tamzen-font#23]
In the screenshots youve posted below what tamzen font are you actually using I cant tell really, Im asking only because I want to download this on my mac love the font btw dont know what ttf it would be

**Comment by sunaku** [comment]
The font used in the Screenshots section of the README is **TamzenForPowerline at size 16** (aka. 8x16).

![TamzenForPowerline8x16r.bdf](https://github.com/sunaku/tamzen-font/raw/master/png/TamzenForPowerline8x16r.png) ![TamzenForPowerline8x16b.bdf](https://github.com/sunaku/tamzen-font/raw/master/png/TamzenForPowerline8x16b.png)
