### ISSUE TITLE
HiPDI support

### ISSUE THREAD

**Issue by moraisaugusto** [sunaku/tamzen-font#24]
Hi.

Is there some plan to increase the font size to HiPDI resolution? I have a 4k monitor and this font does not fit well (super tiny).

**Comment by sunaku** [comment]
Have you tried the TTF variant?  In theory, it should scale beyond the confines of its fixed-size BDF origins.

**Comment by moraisaugusto** [comment]
well... TTF works but does not have powerline support.

**Comment by sunaku** [comment]
The TTF version of this font now properly supports Powerline symbols.  :tipping_hand_man:  See https://github.com/sunaku/tamzen-font/issues/26#issuecomment-625984694. Closing.
