### ISSUE TITLE
Powerline symbols do not render on WSL/mintty

### ISSUE THREAD

**Issue by griendt** [sunaku/tamzen-font#26]
I'm using mintty on my Windows machine. I have installed the Tamzen fonts from the /fnt folder. I could select them perfectly fine, but the Powerline symbols will not render:
![image](https://user-images.githubusercontent.com/15815933/67779342-caf15d00-fa64-11e9-85e8-e0ad445a249c.png)

As you can see, all Powerline symbols seem to be replaced with some ÿ glyph.

Other fonts with Powerline support, such as Inconsolata, will render perfectly fine:
![image](https://user-images.githubusercontent.com/15815933/67779398-e0668700-fa64-11e9-82be-6da5a4cac0dc.png)

I could not try this in the default WSL for Windows 10 (considering its font menu only appears to accept TTF, and there are no TTFs of Tamzen with Powerline symbols (?)).

Considering Powerline support in a bitmap font was the main reason I searched for (and found) this sweet font, it would be awesome to figure out how this could be fixed.

**Comment by griendt** [comment]
I will add: it does not appear to be an issue with the shell itself. If I copy-paste the text output to a random text editor and choose a TamzenForPowerline font, it will still display ÿ symbols instead.

**Comment by pandasauce** [comment]
Every tool out there that I've tried fails to convert Linux bitmap fonts into any of the Windows-compatible formats (TTF, OTF, FON, FNT) without losing support for non-ASCII characters.

List of tools I've attempted:

* bdf2fon
* bdf2ttf
* fontforge
* bdf2psf->psftools' psf2fnt
* convbdf
* [potrace-pixelperfect](https://github.com/koemaeda/potrace-pixelperfect)

This is becoming somewhat a problem for Linux too [now that upstream Pango dropped support for bitmap fonts](https://gitlab.gnome.org/GNOME/pango/issues/386)

There seems to be an unfilled niche for a UTF-8 compatible BDF-to-whatever font converter.

**Comment by sunaku** [comment]
Hi @pandasauce, thanks for your extensive efforts! :+1:    Could you please also check the OTB format?

See https://github.com/sunaku/tamzen-font/issues/25#issuecomment-623059647

**Comment by pandasauce** [comment]
I have since then found that fonts traced with BitFonter and converted to TTF in FontLab with some manual adjustments to metrics (they don't carry over) give pixel-perfect results. It's not cheap though...

**Comment by sunaku** [comment]
Using the TTF version of this font (available in the `ttf/` subfolder), I observe that Powerline symbols are now rendered correctly under a WSL (Ubuntu) session attached to Windows Terminal 0.11.1251.0:

![2020-05-08 12_31_07](https://user-images.githubusercontent.com/9863/81442392-5a6c7c80-9128-11ea-80f5-3c58ac2f5c5d.png)

Therefore, I'm closing issue. :policeman: Please re-open if you still need assistance or find other discrepancies.
