### ISSUE TITLE
Bitmap fontpatcher down

### ISSUE THREAD

**Issue by toniz4** [sunaku/tamzen-font#31]
The link that leads to the bitmap fontpatcher seems down, do you have another link? or the source of the program?

**Comment by sunaku** [comment]
Yes, I have a local Mercurial clone of that project, which I have mirrored for you here:

https://github.com/sunaku/bitmap-font-patcher

The `Rakefile` in this project has also been updated accordingly in 7ea70cc0fdce3e2261d240f1eefe9d3aedd930a.  Cheers.
