### ISSUE TITLE
README: ZyX_I's bitmap-font-patcher link dead

### ISSUE THREAD

**Issue by Nuc1eoN** [sunaku/tamzen-font#32]
It seems the link to [ZyX_I's bitmap-font-patcher](https://bitbucket.org/ZyX_I/bitmap-font-patcher) is dead sadly.

I didn't find an alternative repo link though, however I am actually interested in the software.

Do you know of any alternatives/forks links?

**Comment by Nuc1eoN** [comment]
Found it :) #33

**Comment by sunaku** [comment]
Merged #33 now. Thanks!
