### ISSUE TITLE
Box Drawing Characters

### ISSUE THREAD

**Issue by Nycroth** [sunaku/tamzen-font#6]
I'm wondering if the box drawing characters could be looked at at some point to tidy them up? For some reason, Tamsyn and Tamzen both have a shift artifact that display the characters offset from where they should be. I have never worked directly on fonts so I wouldn't know how to submit a patch or how to fix the issue.

I've attached screenshots from my terminal. I'm running the Suckless terminal (st) and in these examples directly displaying my MOTD and the output of alsamixer. I've also included a large version font running htop.
![screenshot](https://cloud.githubusercontent.com/assets/6979898/14239364/cc37c736-fa08-11e5-9b73-4b70d92722a5.png)

![screenshot](https://cloud.githubusercontent.com/assets/6979898/14239370/da8bd2c8-fa08-11e5-9bd3-dc3c8c52731d.png)

![screenshot](https://cloud.githubusercontent.com/assets/6979898/14239424/941b6c30-fa09-11e5-8a09-e2605a056129.png)

It may be a combination issue with the font and st. However, no other font I've used (Source Code Pro, Terminus, Monaco, Dejavu Sans Mono, or Courier New) have had the same issue.

If there is anything more I can do to help. Don't hesitate to let me know.

**Comment by Nycroth** [comment]
Problem identified, incomplete font specification lead to in-optimal font selection in st.

After changing from, "Tamzen:Size=6" to "Tamzen:style=Regular:slant=0:weight=80:width=100:pixelsize=12:spacing=110:foundry=Misc:antialias=False:index=0:outline=False:scalable=False" everything has been fixed.

To find these, use fc-cat. This will list the call strings for each font (especially useful for bitmap fonts).

**Comment by joaotavora** [comment]
Fantastic :-D
